# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Trivia Trek                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Enhance your knowledge in FBLA while engaging in a fun and adventurous trek through the wilderness!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Homestead FBLA                                
your_link                                 : http://hhsfbla.com/                    
your_city                                 : Cupertino                                
email_address                             : triviatrek@hhsfbla.com
facebook_username                         : homestead8990                                          
instagram_username                        : homesteadfbla
twitter_username                          : homestead_fbla
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Effectiveness
    description                           : Trivia Trek users often report positive feedback, and are both more well-versed AND involved in FBLA!
    fontawesome_icon_name                 : magic
    
  - title                                 : Usability
    description                           : Simple to download, simple to play. Our app-navigation is designed to be as user-friendly as possible.
    fontawesome_icon_name                 : mobile

  - title                                 : Gamification
    description                           : Trivia Trek is very game-centered, setting it apart from typical quiz apps and giving the user a more engaging experience.
    fontawesome_icon_name                 : play-circle

  - title                                 : Infinitely Playable
    description                           : There are infintely many combinations of different questions and games, so once you've completed a game, start a new one!
    fontawesome_icon_name                 : sync

  - title                                 : Customizability
    description                           : You have the option of picking different avatars and game maps each time you play, take your pick!
    fontawesome_icon_name                 : adjust
  
  - title                                 : Social Media
    description                           : Trivia Trek supports full Facebook Integration, allowing you to log in and share your experiences via post or story!
    fontawesome_icon_name                 : star

  - title                                 : Local Progress Tracking
    description                           : Trivia Trek keeps track of your scores and statistics, and allows you to track your progress and improve!
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Connected
    description                           : All of our questions, answers, bug report logs, and analytics are stored in the cloud, which allows for increased flexibility.
    fontawesome_icon_name                 : link

  - title                                 : Tutorials
    description                           : You have access to a more general, as well as a detailed tutorial of Trivia Trek in the app, so we are ready when you are!
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
